"""rename address

Revision ID: 989c1e64633c
Revises: 0c0157463571
Create Date: 2024-07-17 11:08:40.194001

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '989c1e64633c'
down_revision = '0c0157463571'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('departments', 'address',  new_column_name='location')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('departments', 'location',  new_column_name='address')
    # ### end Alembic commands ###
